openapi: 3.0.3
info:
  title: Jupiter Server    
  description: |-
    This is the API definition for the Jupiter server.
  version: 1.0.0
servers:
  - url: /api/v1
    description: "Jupiter-Server"
tags:
  - name: API
    description: DICOM Management
paths:
  /dicoms:
    get:
      tags:
        - API
      summary: Get all Dicoms list
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    dicomId:  
                      type: string
                      example: dicom001
                    patientId:
                      type: string
                      example: partient003
                    studyDate:
                      type: string
                      example: 2024-07-29T08:30:16.757Z
                    modality:
                      type: string
                      example: MRI
                    status:
                      type: string
                      example: unannotated
                  
        500:
          $ref: "#/components/responses/InternalError"
  /dicom/{id}:
    get:
      tags:
        - API
      summary: Get a specific DICOM by ID
      description: Download DICOM file
      parameters:
        - name: id
          in: path
          description: Dicom Id
          required: true
          schema:
            type: string
            example: dicom001
      responses:
        200:
          description: Successfully
          content:
            application/file:
              schema:
                type: string
                format: binary
        500:
          $ref: "#/components/responses/InternalError"
  /annotation/{id}:
    post:
      tags:
        - API
      summary: Upload the annotation file in NII format to the jupiter server.
      parameters:
        - name: id
          in: path
          description: Dicom Id
          required: true
          schema:
            type: string
            example: dicom001
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: Successfully
        500:
          $ref: "#/components/responses/InternalError"
components:
  responses:
    InternalError:
      description: InternalError
      content:
        application/json:
          example:
            message: An unknown error occurred
  
